[project]
name = "load-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "locust>=2.42.5",
    "matplotlib>=3.10.7",
]
